# Generated by Django 3.2.23 on 2023-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_task_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
